# Generated by Django 4.1 on 2023-03-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.URLField(default=None, verbose_name='IMG URL'),
        ),
        migrations.AddField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(default=0, verbose_name='LTE'),
        ),
        migrations.AddField(
            model_name='phone',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='phone',
            name='release_date',
            field=models.TimeField(default=None, verbose_name='Release Date'),
        ),
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True, verbose_name='URL'),
        ),
    ]
